### ISSUE TITLE
Task: create auth routes

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/quackchat#2]
## ✅ Task List
- [x] /signup: Create a new user account.
- [x] /login: Log in to the application.
- [x] /logout: Log out from the application.
