### ISSUE TITLE
Task: create chatroom routes

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/quackchat#3]
## ✅ Task List
- [ ] /chatrooms: Get a list of available chatrooms.
- [x] /chatrooms/create: Create a new chatroom.
- [ ] /chatrooms/{chatroomId}: Get details of a specific chatroom.
- [x] /chatrooms/{chatroomId}/join: Join a specific chatroom.
- [x] /chatrooms/{chatroomId}/leave: Leave a specific chatroom.
- [ ] /chatrooms/{chatroomId}/users: Get the list of users in a specific chatroom
